services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"
    volumes:
        - postgres:/var/lib/postgresql/data
  core:
    restart: always
    depends_on:
        - "postgres"
    container_name: core
    build:
        dockerfile: Dockerfile
        context: .
    environment:
      POSTGRES: postgresql://username:password@postgres:5432/test?sslmode=disable
      HOST: 0.0.0.0:8088
    ports:
      - '8088:8088'
volumes:
  postgres: